name: Build and Push Almeida Monorepo
run-name: Build default - ${{ gitea.actor }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to Gitea Registry
        uses: docker/login-action@v2
        with:
          registry: gitea.nilbyte.com.br
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # Build Backend
      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: apps/back-end/Dockerfile
          push: true
          tags: gitea.nilbyte.com.br/${{ gitea.repository }}/backend:latest

      # Build Backoffice
      - name: Build and push Backoffice image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: apps/back-office/Dockerfile
          build-args: |
            VITE_API_URL=https://api.almeida.nilbyte.com.br
          push: true
          tags: gitea.nilbyte.com.br/${{ gitea.repository }}/backoffice:latest

      - name: Deploy to Homelab
        run: |
          # Define environment variable for docker-compose to match the image tags
          export GITEA_REPOSITORY=${{ gitea.repository }}

          # Pull the latest images
          docker compose pull

          # Restart containers with the new images
          docker compose up -d
