name: Build and Push Almeida Monorepo
run-name: Build default - ${{ gitea.actor }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y ca-certificates curl gnupg
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
            tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update
          apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Configure Git
        run: |
          git config --global user.name "Continuous Integration"
          git config --global user.email "ci@nilbyte.com.br"

      - name: Version Bump
        run: |
          npx -y standard-version --message "chore(release): %s [skip ci]"
          git push --follow-tags origin HEAD:main

      # PASSO NOVO: Converter o nome do repositório para minúsculo
      - name: Lowercase Repository Name
        run: |
          echo "REPO_LOWER=$(echo '${{ gitea.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to Gitea Registry
        uses: docker/login-action@v2
        with:
          registry: gitea.nilbyte.com.br
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # Build Backend (Usando env.REPO_LOWER)
      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: apps/back-end/Dockerfile
          push: true
          # AQUI MUDOU: De ${{ gitea.repository }} para ${{ env.REPO_LOWER }}
          tags: gitea.nilbyte.com.br/${{ env.REPO_LOWER }}/backend:latest
          no-cache: true

      # Build Backoffice (Usando env.REPO_LOWER)
      - name: Build and push Backoffice image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: apps/back-office/Dockerfile
          build-args: |
            VITE_API_URL=https://api.almeida.nilbyte.com.br
          push: true
          tags: gitea.nilbyte.com.br/${{ env.REPO_LOWER }}/backoffice:latest
          no-cache: true

      - name: Deploy to Server
        run: |
          # 1. Exportar a variável para taggear a imagem correta (MINÚSCULA)
          # Isso é importante para o docker-compose achar a imagem que acabamos de subir
          export GITEA_REPOSITORY=${{ env.REPO_LOWER }}

          # 2. Criar o arquivo .env com as secrets do Gitea
          echo "DATABASE_URL=postgresql://${{ secrets.ALMEIDA_DB_USER }}:${{ secrets.ALMEIDA_DB_PASSWORD }}@tailscale:5433/${{ secrets.ALMEIDA_DB_NAME }}" >> .env
          echo "JWT_SECRET=${{ secrets.ALMEIDA_JWT_SECRET }}" >> .env

          # Variável de produção
          echo "NODE_ENV=production" >> .env

          # 3. Pull e Up
          docker compose pull
          docker compose up -d
